/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/liff/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exchangeLiffIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/active-shelter-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActiveShelterContext"];
        put: operations["switchActiveShelterContext"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrganizations"];
        put?: never;
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateOrganization"];
        trace?: never;
    };
    "/v1/organizations/{organizationId}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disableOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{organizationId}/initial-admin": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createInitialShelterAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{organizationId}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get: operations["listMemberships"];
        put?: never;
        post: operations["createMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{organizationId}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createOrganizationAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{organizationId}/memberships/{membershipId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                membershipId: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMembership"];
        trace?: never;
    };
    "/v1/organizations/{organizationId}/areas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get: operations["listShelterAreas"];
        put?: never;
        post: operations["createShelterArea"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{organizationId}/areas/{areaId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                areaId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateShelterArea"];
        trace?: never;
    };
    "/v1/animals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReportableAnimals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/animals/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchAnimalsByShelterNumber"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/qr-tokens/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveQrToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/animals/{animalId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmAnimal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/care-report-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCareReportDrafts"];
        put?: never;
        post: operations["createCareReportDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/care-report-drafts/{draftId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        get: operations["getCareReportDraft"];
        put?: never;
        post?: never;
        delete: operations["deleteCareReportDraft"];
        options?: never;
        head?: never;
        patch: operations["updateCareReportDraft"];
        trace?: never;
    };
    "/v1/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        get: operations["getMediaStatus"];
        put?: never;
        post?: never;
        delete: operations["deleteTemporaryMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/media/{mediaId}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSignedDownloadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/care-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCareReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/care-reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        get: operations["getCareReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["correctCareReport"];
        trace?: never;
    };
    "/v1/care-reports/{reportId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveCareReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/animals/{animalId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnimalTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observation-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listObservationCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observation-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listObservationOptions"];
        put?: never;
        post: operations["createObservationOption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observation-options/{optionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                optionId: components["parameters"]["OptionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateObservationOption"];
        trace?: never;
    };
    "/v1/observation-options/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reorderObservationOptions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/care-reports/{reportId}/ai-observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAiObservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai-observations/{observationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAiObservation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai-observations/{observationId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reviewAiObservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/line/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description LINE Messaging API Webhook 邊界。伺服器必須先以未修改的原始 Request Body 與 X-Line-Signature 驗證簽章，再解析事件；事件依 webhookEventId 冪等處理。 Webhook 本身不代表 CRM 使用者已取得回報權限；系統必須依 LINE Binding、唯一 Webhook Session 或唯一 Shelter Context 重新判定是否可以開始回報，多個候選不得自動選擇。 */
        post: operations["receiveLineWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/line/bind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description FastAPI 驗證 LINE 身分後，將其對應既有 User 與有效 Membership；不得自動建立正式 Membership。 */
        post: operations["bindLineIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/line/rich-menu/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLineRichMenuContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/line/care-report/drafts/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentLineCareReportDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/line/care-report/drafts/{draftId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeLineCareReportDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/line/care-report/drafts/{draftId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelLineCareReportDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            code: string;
            message: string;
            request_id: string;
            details?: {
                [key: string]: unknown;
            };
        };
        LineWebhookRequest: {
            destination: string;
            events: components["schemas"]["LineWebhookEvent"][];
        };
        LineWebhookEvent: {
            /** @enum {string} */
            type: "message" | "postback" | "follow" | "unfollow" | "beacon" | "join" | "memberJoined" | "memberLeft" | "accountLink" | "things";
            webhookEventId: string;
            /** Format: int64 */
            timestamp: number;
            source: {
                [key: string]: unknown;
            };
            deliveryContext?: {
                isRedelivery?: boolean;
            };
            message?: {
                [key: string]: unknown;
            };
            postback?: {
                [key: string]: unknown;
            };
        };
        LineWebhookResponse: {
            accepted: boolean;
            event_results: {
                webhook_event_id: string;
                /** @enum {string} */
                status: "processed" | "duplicate_ignored" | "signature_rejected" | "requires_liff" | "rejected" | "failed";
                reason?: string | null;
                webhook_session?: components["schemas"]["WebhookSession"];
                /** @enum {string|null} */
                next_action?: "resume_report" | "bind_line_identity" | "select_shelter_in_liff" | null;
            }[];
        };
        LineBindRequest: {
            id_token: string;
        };
        LineBindResponse: {
            session: components["schemas"]["AuthResponse"];
        };
        RichMenuContext: {
            /** @enum {string} */
            context_status: "single_context" | "multiple_contexts" | "no_context" | "requires_liff";
            /** Format: uuid */
            organization_id?: string | null;
            /** Format: uuid */
            webhook_session_id?: string | null;
            actions: {
                code: string;
                display_name: string;
                /** @enum {string} */
                action_type?: "postback" | "uri" | "camera" | "camera_roll" | "message";
            }[];
        };
        CurrentLineDraftResponse: {
            draft: components["schemas"]["Draft"] | null;
        };
        ResumeDraftRequest: {
            draft_token?: string;
        };
        CancelDraftRequest: {
            reason: string;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        LiffExchangeRequest: {
            id_token: string;
        };
        AuthResponse: {
            access_token: string;
            /** @example 900 */
            expires_in: number;
            /** Format: uuid */
            session_id: string;
            /** @description 登入帳號可選擇的有效收容所，供前端建立 Active Context。 */
            organizations?: components["schemas"]["LoginOrganization"][];
            user: components["schemas"]["User"];
        };
        LoginOrganization: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** @enum {string} */
            role: "SHELTER_ADMIN" | "STAFF" | "VOLUNTEER";
        };
        AccessScope: {
            /** @enum {string} */
            type: "PLATFORM" | "SHELTER";
            organization_ids?: string[];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "active" | "disabled";
            roles: ("PLATFORM_ADMIN" | "SHELTER_ADMIN" | "STAFF" | "VOLUNTEER")[];
            scope: components["schemas"]["AccessScope"];
        };
        CurrentUserResponse: {
            user: components["schemas"]["User"];
            memberships: components["schemas"]["Membership"][];
        };
        ActiveShelterContext: {
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            session_id: string;
        };
        WebhookSession: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            system_user_id: string;
            /** Format: uuid */
            organization_id?: string | null;
            /** @enum {string} */
            status: "active" | "revoked" | "expired" | "requires_liff";
            /** Format: uuid */
            active_shelter_context_id?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            last_interaction_at?: string;
        };
        ShelterContextSwitchRequest: {
            /** Format: uuid */
            organization_id: string;
        };
        Organization: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** @enum {string} */
            status: "pending_setup" | "active" | "suspended";
        };
        OrganizationCreateRequest: {
            code: string;
            name: string;
            /** @enum {string} */
            status: "pending_setup";
            initial_admin_username: string;
            /** Format: password */
            initial_admin_temporary_password: string;
            address?: string;
            service_area?: string;
            contact?: string;
        };
        InitialAdminCreateRequest: {
            username: string;
            /** Format: password */
            temporary_password: string;
        };
        OrganizationUpdateRequest: {
            name?: string;
            address?: string;
            service_area?: string;
            contact?: string;
            /** @enum {string} */
            status?: "pending_setup" | "active" | "suspended";
        };
        OrganizationListResponse: {
            items: components["schemas"]["Organization"][];
        };
        Membership: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            user_id: string;
            /** @enum {string} */
            role: "SHELTER_ADMIN" | "STAFF" | "VOLUNTEER";
            /** @enum {string} */
            status: "invited" | "active" | "disabled";
        };
        MembershipCreateRequest: {
            /** Format: uuid */
            user_id: string;
            /** @enum {string} */
            role: "SHELTER_ADMIN" | "STAFF" | "VOLUNTEER";
        };
        MembershipUpdateRequest: {
            /** @enum {string} */
            role?: "SHELTER_ADMIN" | "STAFF" | "VOLUNTEER";
            /** @enum {string} */
            status?: "invited" | "active" | "disabled";
        };
        MembershipListResponse: {
            items: components["schemas"]["Membership"][];
        };
        AccountCreateRequest: {
            username: string;
            display_name: string;
            /** Format: password */
            temporary_password: string;
            /** @enum {string} */
            role: "SHELTER_ADMIN" | "STAFF" | "VOLUNTEER";
        };
        ShelterArea: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            name: string;
            /** @enum {string} */
            area_type: "area" | "cage";
            /** Format: uuid */
            parent_id?: string | null;
            /** @enum {string} */
            status: "active" | "inactive";
        };
        ShelterAreaCreateRequest: {
            name: string;
            /**
             * @default area
             * @enum {string}
             */
            area_type: "area" | "cage";
            /** Format: uuid */
            parent_id?: string | null;
        };
        ShelterAreaUpdateRequest: {
            name?: string;
            /** @enum {string} */
            area_type?: "area" | "cage";
            /** Format: uuid */
            parent_id?: string | null;
            /** @enum {string} */
            status?: "active" | "inactive";
        };
        ShelterAreaListResponse: {
            items: components["schemas"]["ShelterArea"][];
        };
        AnimalCandidate: {
            /** Format: uuid */
            id: string;
            name: string;
            shelter_number?: string | null;
            /** Format: uri */
            photo_url?: string | null;
            cage?: string | null;
            area?: string | null;
            /** Format: uuid */
            organization_id: string;
            can_report: boolean;
        };
        AnimalConfirmationResponse: components["schemas"]["AnimalCandidate"] & {
            confirmation_token: string;
        };
        AnimalListResponse: {
            items: components["schemas"]["AnimalCandidate"][];
            page: number;
            page_size: number;
        };
        QrResolveRequest: {
            qr_token: string;
        };
        DraftCreateRequest: {
            /** Format: uuid */
            animal_id: string;
            confirmation_token: string;
        };
        /**
         * @description 照護完成狀態；未觀察與無法判斷不得解讀為已完成
         * @enum {string}
         */
        CareCompletionCode: "care_completion.completed" | "care_completion.partially_completed" | "care_completion.not_provided" | "care_completion.not_observed" | "care_completion.uncertain";
        /**
         * @description 散步完成狀態；與散步反應的 walk.* 選項分開
         * @enum {string}
         */
        WalkCompletionCode: "walk_completion.completed" | "walk_completion.partially_completed" | "walk_completion.not_done" | "walk_completion.not_observed" | "walk_completion.uncertain";
        /** @description 由 CRM 有效 Observation Vocabulary 提供的穩定 Code；顯示名稱不得作為正式值 */
        ObservationAnswerCode: string;
        /** @description 可逐題保存的標準回報答案；草稿階段允許不完整，正式送出時必須符合 CareReportAnswers */
        DraftAnswers: {
            care_completion?: components["schemas"]["CareCompletionCode"];
            walk_completion?: components["schemas"]["WalkCompletionCode"];
            feeding?: components["schemas"]["ObservationAnswerCode"];
            water?: components["schemas"]["ObservationAnswerCode"];
            activity?: components["schemas"]["ObservationAnswerCode"];
            urination?: components["schemas"]["ObservationAnswerCode"];
            defecation?: components["schemas"]["ObservationAnswerCode"];
            resource_guarding?: components["schemas"]["ObservationAnswerCode"];
            human_interaction?: components["schemas"]["ObservationAnswerCode"];
            animal_interaction?: components["schemas"]["ObservationAnswerCode"];
            emotion?: components["schemas"]["ObservationAnswerCode"];
            walk_reaction?: components["schemas"]["ObservationAnswerCode"];
            appearance_special_status?: components["schemas"]["ObservationAnswerCode"];
        } & {
            [key: string]: unknown;
        };
        /** @description 正式 Care Report 必須完整包含的標準結構化答案；照片與心得不在此必要集合 */
        CareReportAnswers: components["schemas"]["DraftAnswers"] & Record<string, never>;
        DraftUpdateRequest: {
            /** @description 可只包含目前新增或修改的答案；後端依 Draft 目前狀態驗證，不接受跳步或略過必要題目 */
            answers?: components["schemas"]["DraftAnswers"];
            note?: string;
            media_ids?: string[];
        };
        Draft: {
            /** Format: uuid */
            id: string;
            opaque_token: string | null;
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            animal_id: string;
            /** Format: uuid */
            volunteer_user_id: string;
            /** Format: uuid */
            membership_id: string;
            /** @enum {string} */
            current_step: "selecting_animal" | "confirming_animal" | "answering_completion" | "answering_feeding" | "answering_water" | "answering_activity" | "answering_elimination" | "answering_behavior" | "answering_special_status" | "awaiting_media" | "awaiting_note" | "reviewing" | "submitting" | "submitted" | "cancelled" | "expired";
            answers: components["schemas"]["DraftAnswers"];
            media_ids?: string[];
            /** Format: date-time */
            last_interaction_at?: string;
            /** Format: date-time */
            expires_at: string;
            /** @enum {string} */
            status: "active" | "submitted" | "cancelled" | "expired";
        };
        DraftListResponse: {
            items: components["schemas"]["Draft"][];
        };
        MediaAsset: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** @enum {string} */
            status: "temporary" | "processing" | "processed" | "attached" | "failed" | "unusable" | "archived";
            /** @constant */
            exif_removed: true;
            checksum?: string;
            purpose?: string;
        };
        SignedUrlResponse: {
            /** Format: uri */
            url: string;
            /** Format: date-time */
            expires_at: string;
        };
        CareReportCreateRequest: {
            /** Format: uuid */
            draft_id: string;
            /** @description 標準回報完整結構化答案；照片與心得不屬於必要欄位 */
            observations: components["schemas"]["CareReportAnswers"];
            note?: string;
            media_ids?: string[];
        };
        CareReportCorrectionRequest: {
            reason: string;
            observations?: {
                [key: string]: unknown;
            };
            note?: string;
            /** Format: uuid */
            animal_id?: string;
        };
        ArchiveRequest: {
            reason: string;
        };
        CareReport: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            animal_id: string;
            /** @enum {string} */
            status: "saved" | "amended" | "archived";
            observations: components["schemas"]["CareReportAnswers"];
            observation_snapshots?: {
                [key: string]: {
                    [key: string]: string;
                };
            } | null;
            /** Format: date-time */
            created_at: string;
        };
        TimelineResponse: {
            days: {
                /** Format: date */
                date: string;
                has_report: boolean;
                report_count: number;
                /** @example 當日無回報 */
                no_report_label?: string | null;
                reports?: components["schemas"]["TimelineReport"][];
            }[];
        };
        TimelineReport: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            submitted_at: string;
            /** Format: uuid */
            volunteer_user_id: string;
            animal_name_snapshot: string;
            shelter_number_snapshot?: string | null;
            note?: string | null;
            observations: {
                [key: string]: string;
            };
            observation_snapshots: {
                [key: string]: {
                    [key: string]: string;
                };
            } | null;
            /** @enum {string} */
            status: "saved" | "amended" | "archived";
            ai_job_status: string;
            media_ids: string[];
        };
        ObservationCategoryListResponse: {
            items: components["schemas"]["ObservationCategory"][];
        };
        ObservationCategory: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id?: string | null;
            code: string;
            display_name: string;
            description?: string;
            /** @enum {string} */
            status: "active" | "disabled";
            display_order: number;
            /** @enum {string} */
            source: "platform_default" | "organization_extension";
        };
        ObservationOption: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            category_id: string;
            /** Format: uuid */
            organization_id?: string | null;
            code: string;
            display_name: string;
            description?: string;
            /** @enum {string} */
            status: "active" | "disabled";
            enabled: boolean;
            display_order: number;
            requires_note?: boolean;
            /** @enum {string} */
            source: "platform_default" | "organization_extension";
            editable: boolean;
        };
        ObservationOptionCreateRequest: {
            /** Format: uuid */
            category_id: string;
            code: string;
            display_name: string;
            /** @default  */
            description: string;
            /** @default 0 */
            display_order: number;
            /** @default false */
            requires_note: boolean;
        };
        ObservationOptionUpdateRequest: {
            display_name?: string;
            description?: string;
            display_order?: number;
            enabled?: boolean;
        };
        ObservationOptionReorderItem: {
            /** Format: uuid */
            option_id: string;
            display_order: number;
        };
        ObservationOptionReorderRequest: {
            items: components["schemas"]["ObservationOptionReorderItem"][];
        };
        ObservationOptionListResponse: {
            items: components["schemas"]["ObservationOption"][];
        };
        AiObservation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            job_id: string;
            /** @enum {string} */
            source_type: "note" | "photo";
            /** Format: uuid */
            source_id: string | null;
            /** @enum {string} */
            status: "pending" | "running" | "succeeded" | "failed" | "invalid" | "confirmed" | "rejected" | "corrected";
            provider: string;
            model_name: string;
            model_version: string;
            prompt_template_id: string;
            prompt_version: string;
            output_schema_version: string;
            raw_ai_output: {
                [key: string]: unknown;
            } | unknown[] | string | null;
            validation_result: {
                [key: string]: unknown;
            } | null;
            validated_ai_observation: {
                [key: string]: unknown;
            } | null;
            human_review_result: {
                [key: string]: unknown;
            } | null;
            /** Format: uuid */
            reviewed_by?: string | null;
            /** Format: date-time */
            reviewed_at?: string | null;
            failure_reason: string | null;
        };
        AiObservationListResponse: {
            items: components["schemas"]["AiObservation"][];
        };
        AiReviewRequest: {
            /** @enum {string} */
            action: "confirm" | "reject" | "correct";
            reason: string;
            corrected_observation?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Webhook 或 Request 格式錯誤 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 本系統 Session 憑證 */
        AuthResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthResponse"];
            };
        };
        /** @description 未通過身分驗證 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 無權限或無法存取，不能洩漏資源存在性 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 不存在或未授權的一致結果 */
        NotFoundOrForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Idempotency 或資料狀態衝突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 日期區間或欄位驗證失敗 */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        OrganizationId: string;
        MembershipId: string;
        AnimalId: string;
        DraftId: string;
        MediaId: string;
        ReportId: string;
        OptionId: string;
        ObservationId: string;
        IdempotencyKey: string;
        LineSignature: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["AuthResponse"];
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            200: components["responses"]["AuthResponse"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session 已撤銷 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目前使用者與 Membership */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    exchangeLiffIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiffExchangeRequest"];
            };
        };
        responses: {
            200: components["responses"]["AuthResponse"];
            403: components["responses"]["Forbidden"];
        };
    };
    getActiveShelterContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目前 Session 的 Active Shelter Context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveShelterContext"];
                };
            };
        };
    };
    switchActiveShelterContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShelterContextSwitchRequest"];
            };
        };
        responses: {
            /** @description 切換後的 Active Shelter Context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveShelterContext"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 依角色可見的收容所 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationListResponse"];
                };
            };
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreateRequest"];
            };
        };
        responses: {
            /** @description 收容所已建立，預設未啟用 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 收容所資料 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            404: components["responses"]["NotFoundOrForbidden"];
        };
    };
    updateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdateRequest"];
            };
        };
        responses: {
            /** @description 收容所已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    disableOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 收容所已停用 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createInitialShelterAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitialAdminCreateRequest"];
            };
        };
        responses: {
            /** @description 初始收容所管理員帳號已建立 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listMemberships: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 收容所 Membership */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipListResponse"];
                };
            };
        };
    };
    createMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipCreateRequest"];
            };
        };
        responses: {
            /** @description Membership 已建立 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createOrganizationAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreateRequest"];
            };
        };
        responses: {
            /** @description 收容所帳號與 Membership 已建立 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    updateMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                membershipId: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipUpdateRequest"];
            };
        };
        responses: {
            /** @description Membership 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listShelterAreas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 收容所 Cage/Area 清單 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelterAreaListResponse"];
                };
            };
        };
    };
    createShelterArea: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShelterAreaCreateRequest"];
            };
        };
        responses: {
            /** @description Cage/Area 已建立 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelterArea"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    updateShelterArea: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                areaId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShelterAreaUpdateRequest"];
            };
        };
        responses: {
            /** @description Cage/Area 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelterArea"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listReportableAnimals: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目前 Active Shelter Context 內的授權 Animal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalListResponse"];
                };
            };
        };
    };
    searchAnimalsByShelterNumber: {
        parameters: {
            query: {
                query: string;
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 授權範圍內的候選 Animal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalListResponse"];
                };
            };
        };
    };
    resolveQrToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QrResolveRequest"];
            };
        };
        responses: {
            /** @description 唯一候選 Animal 確認卡資料 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalCandidate"];
                };
            };
            404: components["responses"]["NotFoundOrForbidden"];
        };
    };
    confirmAnimal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animalId: components["parameters"]["AnimalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已確認的 Animal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalConfirmationResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listCareReportDrafts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 本人可見 Draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftListResponse"];
                };
            };
        };
    };
    createCareReportDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftCreateRequest"];
            };
        };
        responses: {
            /** @description Draft 已建立 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
        };
    };
    getCareReportDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
        };
    };
    deleteCareReportDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft 已刪除或進入清理流程 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCareReportDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftUpdateRequest"];
            };
        };
        responses: {
            /** @description Draft 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
        };
    };
    uploadMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: uuid */
                    draft_id: string;
                    /** @enum {string} */
                    purpose: "elimination" | "fur" | "appearance" | "activity" | "other";
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Media 處理狀態 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAsset"];
                };
            };
        };
    };
    getMediaStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media 狀態 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAsset"];
                };
            };
        };
    };
    deleteTemporaryMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 尚未提交的 Temporary Media 已刪除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createSignedDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 短效 Signed URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedUrlResponse"];
                };
            };
        };
    };
    createCareReport: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CareReportCreateRequest"];
            };
        };
        responses: {
            /** @description 原始 Care Report 已保存 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareReport"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getCareReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Care Report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareReport"];
                };
            };
        };
    };
    correctCareReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CareReportCorrectionRequest"];
            };
        };
        responses: {
            /** @description Care Report 已修正或封存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareReport"];
                };
            };
        };
    };
    archiveCareReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        responses: {
            /** @description Care Report 已封存並留下 Audit Record */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAnimalTimeline: {
        parameters: {
            query?: {
                start_date?: string;
                end_date?: string;
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                animalId: components["parameters"]["AnimalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 每日摘要與逐筆 Timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFoundOrForbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listObservationCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 觀察類別 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationCategoryListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listObservationOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目前可用與歷史 Observation Option */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationOptionListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createObservationOption: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationOptionCreateRequest"];
            };
        };
        responses: {
            /** @description Observation Option 已建立 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationOption"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    updateObservationOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                optionId: components["parameters"]["OptionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationOptionUpdateRequest"];
            };
        };
        responses: {
            /** @description Observation Option 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationOption"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFoundOrForbidden"];
        };
    };
    reorderObservationOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationOptionReorderRequest"];
            };
        };
        responses: {
            /** @description Observation Option 順序已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationOptionListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFoundOrForbidden"];
        };
    };
    listAiObservations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI Observation 與處理狀態 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiObservationListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFoundOrForbidden"];
        };
    };
    getAiObservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                observationId: components["parameters"]["ObservationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI Observation 與來源、版本及覆核狀態 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiObservation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFoundOrForbidden"];
        };
    };
    reviewAiObservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                observationId: components["parameters"]["ObservationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiReviewRequest"];
            };
        };
        responses: {
            /** @description AI Observation 已確認、拒絕或修正 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiObservation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFoundOrForbidden"];
            422: components["responses"]["BadRequest"];
        };
    };
    receiveLineWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-Line-Signature": components["parameters"]["LineSignature"];
            };
            path?: never;
            cookie?: never;
        };
        /** @description 必須保留未修改的原始 Request Body，並在 JSON 解析前搭配 X-Line-Signature 完成驗證。 */
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineWebhookRequest"];
            };
        };
        responses: {
            /** @description 已接受、已忽略重送或已安全處理事件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineWebhookResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    bindLineIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineBindRequest"];
            };
        };
        responses: {
            /** @description 已建立本系統 Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineBindResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getLineRichMenuContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目前 Active Shelter Context 可用的 Rich Menu Action */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RichMenuContext"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getCurrentLineCareReportDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目前 Organization 的 active Draft；不存在時回傳空值 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentLineDraftResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    resumeLineCareReportDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ResumeDraftRequest"];
            };
        };
        responses: {
            /** @description Draft 已恢復至其目前合法步驟 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    cancelLineCareReportDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelDraftRequest"];
            };
        };
        responses: {
            /** @description Draft 已取消且不會建立正式回報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
}
