import {
  AlertTriangle,
  ArrowLeft,
  ChevronDown,
  ChevronRight,
  Edit3,
  ExternalLink,
  Eye,
  FileSearch,
  HelpCircle,
  History,
  KeyRound,
  CalendarDays,
  Menu,
  Pencil,
  RefreshCw,
  Search,
  Settings,
  ShieldAlert,
  Sparkles,
  X,
} from "lucide-react";

export const iconMap = {
  search: Search,
  back: ArrowLeft,
  expand: ChevronDown,
  collapse: ChevronRight,
  edit: Edit3,
  pencil: Pencil,
  retry: RefreshCw,
  settings: Settings,
  ai: Sparkles,
  permission: ShieldAlert,
  navigate: ExternalLink,
  view: Eye,
  history: History,
  menu: Menu,
  close: X,
  alert: AlertTriangle,
  help: HelpCircle,
  audit: FileSearch,
  access: KeyRound,
  calendar: CalendarDays,
} as const;

export type IconName = keyof typeof iconMap;
